language: "en-US"
tone_instructions: "Act as a thoughtful senior engineer reviewing code for a hackathon."
early_access: false
enable_free_tier: true
reviews:
  profile: "assertive"
  auto_review:
    enabled: true
